version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./database:/var/www/html/database
      - ./logs:/var/www/html/logs
    environment:
      - PHP_MEMORY_LIMIT=256M
      - PHP_MAX_EXECUTION_TIME=120
    restart: unless-stopped 